#Florida provides two _zip files: Voter Extract and Voter History_ Depending on the vintage they will have different naming conventions (most recently the files are "Voter_Registration_20180510_zip" and "Voter_History_20180510_zip"_ Both zips contain 67 separate _txt files, one for each county_ "ALA_20061010_txt" would be for Alachua county from Oct 10 2006_ These files DO NOT have headers_
file_type: txt
state: iowa
source: boe
file_class: voter_file
has_headers: No
voter_id: REGN_NUM
county_identifier: COUNTY
birthday_identifier: BIRTHDATE
voter_status: VOTERSTATUS
voter_status_active: Active
voter_status_inactive: Inactive
democratic_party: DEM
republican_party: REP
no_party_affiliation: NP
party_identifier: PARTY
missing_required_fields: true
numeric_county: false
date_format: '%Y%m%d'
generated_columns:
  all_history: text[]
  sparse_history: int[]
ordered_generated_columns:
  - all_history
  - sparse_history
name_fields:
  - cde_name_title
  - text_name_first
  - text_name_middle
  - text_name_last
  - cde_name_suffix
address_fields:
  - HOUSE_NUM
  - HOUSE_SUFFIX
  - PRE_DIR
  - STREET_NAME
  - STREET_TYPE
  - POST_DIR
  - UNIT_TYPE
  - UNIT_NUM
  - ADDRESS_NON_STD
  - CITY
  - STATE
  - ZIP_CODE
  - ZIP_PLUS
primary_key:
  - pre_date
  - post_date
  - REGN_NUM
  - change_type
base_columns:
  pre_date: timestamp
  post_date: timestamp
  REGN_NUM: text
  change_type: text
  pre_value: text
  post_value: text
  state: text
additional_snapshot_columns:
  all_history: text[]
  general_history: text[]
  special_history: text[]
  primary_history: text[]
summary_columns:
  - totals
  - date
  - state
  - ages_18_34
  - ages_35_49
  - ages_50_64
  - ages_65_130
  - r
  - npa
  - d
  - g
  - l
  - c
  - n
  - county
summary_types:
  - int
  - timestamp
  - text
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - varchar
format:
  separate_hist: false
  separate_counties_voter_file: false
  separate_counties_hist_file: false
  hist_election_rows: true
  columnar_elections: false
columns:
  REGN_NUM: text
  FIRST_NAME: text
  MIDDLE_NAME: text
  LAST_NAME: text
  NAME_SUFFIX: text
  EFF_REGN_DATE: date
  LAST_UPDATED_DATE: date
  OLD_ID: text
  PHONENO: text
  HOUSE_NUM: text
  HOUSE_SUFFIX: text
  PRE_DIR: text
  STREET_NAME: text
  STREET_TYPE: text
  POST_DIR: text
  UNIT_TYPE: text
  UNIT_NUM: text
  ADDRESS_NON_STD: text
  CITY_1: text
  STATE_1: text
  ZIP_CODE_1: text
  ZIP_PLUS_1: text
  MAILING_ADDRESS: text
  CITY_2: text
  STATE_2: text
  ZIP_CODE_2: text
  ZIP_PLUS_2: text
  VOTERSTATUS: text
  PARTY: text
  POLITICAL_ORGANIZATION: text
  GENDER: text
  BIRTHDATE: text
  COUNTY: text
  FEDERAL: text
  CONGRESSIONAL: text
  STATEWIDE: text
  STATE_SENATE: text
  STATE_HOUSE: text
  JUDICIAL: text
  PRECINCT: text
  COUNTY_SUPERVISOR: text
  COUNTYWIDE: text
  TOWNSHIP: text
  CITY_COUNCIL_WARD: text
  CITY_3: text
  COMMUNITY_COLLEGE_DIRECTOR: text
  COMMUNITY_COLLEGE: text
  SCHOOL_DIRECTOR: text
  SCHOOL: text
  SANITARY: text
  AGRICULTURAL_EXTENSION: text
  SOIL_AND_WATER: text
  WATER: text
  FIRE: text
  LAND: text
  LAKE: text
  LOSST_CONTIGUOUS_CITIES: text
  RECREATIONAL: text
  RURAL_IMPROVEMENT_ZONE: text
  SEWER: text
  LIGHT: text
  MISCELLANEOUS: text
  GENERAL_ELECTION_DATE: date
  GENERAL_VOTERVOTEMETHOD: text
  GENERAL_ELECTION_DATE_1: date
  GENERAL_VOTERVOTEMETHOD_1: text
  GENERAL_ELECTION_DATE_2: date
  GENERAL_VOTERVOTEMETHOD_2: text
  GENERAL_ELECTION_DATE_3: date
  GENERAL_VOTERVOTEMETHOD_3: text
  GENERAL_ELECTION_DATE_4: date
  GENERAL_VOTERVOTEMETHOD_4: text
  PRIMARY_ELECTION_DATE: date
  PRIMARY_VOTERVOTEMETHOD: text
  POLITICAL_PARTY: text
  POLITICAL_ORGANIZATION_1: text
  PRIMARY_ELECTION_DATE_1: date
  PRIMARY_VOTERVOTEMETHOD_1: text
  POLITICAL_PARTY_1: text
  POLITICAL_ORGANIZATION_2: text
  PRIMARY_ELECTION_DATE_2: date
  PRIMARY_VOTERVOTEMETHOD_2: text
  POLITICAL_PARTY_2: text
  POLITICAL_ORGANIZATION_3: text
  PRIMARY_ELECTION_DATE_3: date
  PRIMARY_VOTERVOTEMETHOD_3: text
  POLITICAL_PARTY_3: text
  POLITICAL_ORGANIZATION_4: text
  PRIMARY_ELECTION_DATE_4: date
  PRIMARY_VOTERVOTEMETHOD_4: text
  POLITICAL_PARTY_4: text
  POLITICAL_ORGANIZATION_5: text
  SCHOOL_ELECTION_DATE: date
  SCHOOL_VOTERVOTEMETHOD: text
  SCHOOL_ELECTION_DATE_1: date
  SCHOOL_VOTERVOTEMETHOD_1: text
  SCHOOL_ELECTION_DATE_2: date
  SCHOOL_VOTERVOTEMETHOD_2: text
  SCHOOL_ELECTION_DATE_3: date
  SCHOOL_VOTERVOTEMETHOD_3: text
  SCHOOL_ELECTION_DATE_4: date
  SCHOOL_VOTERVOTEMETHOD_4: text
  CITY_ELECTION_DATE: date
  CITY_VOTERVOTEMETHOD: text
  CITY_ELECTION_DATE_1: date
  CITY_VOTERVOTEMETHOD_1: text
  CITY_ELECTION_DATE_2: date
  CITY_VOTERVOTEMETHOD_2: text
  CITY_ELECTION_DATE_3: date
  CITY_VOTERVOTEMETHOD_3: text
  CITY_ELECTION_DATE_4: date
  CITY_VOTERVOTEMETHOD_4: text
  SPECIAL_ELECTION_DATE: date
  SPECIAL_VOTERVOTEMETHOD: text
  SPECIAL_ELECTION_DATE_1: date
  SPECIAL_VOTERVOTEMETHOD_1: text
  SPECIAL_ELECTION_DATE_2: date
  SPECIAL_VOTERVOTEMETHOD_2: text
  SPECIAL_ELECTION_DATE_3: date
  SPECIAL_VOTERVOTEMETHOD_3: text
  SPECIAL_ELECTION_DATE_4: date
  SPECIAL_VOTERVOTEMETHOD_4: text
election_columns:
  - GENERAL_ELECTION_DATE
  - GENERAL_VOTERVOTEMETHOD
  - GENERAL_ELECTION_DATE_1
  - GENERAL_VOTERVOTEMETHOD_1
  - GENERAL_ELECTION_DATE_2
  - GENERAL_VOTERVOTEMETHOD_2
  - GENERAL_ELECTION_DATE_3
  - GENERAL_VOTERVOTEMETHOD_3
  - GENERAL_ELECTION_DATE_4
  - GENERAL_VOTERVOTEMETHOD_4
  - PRIMARY_ELECTION_DATE
  - PRIMARY_VOTERVOTEMETHOD
  - POLITICAL_PARTY
  - POLITICAL_ORGANIZATION_1
  - PRIMARY_ELECTION_DATE_1
  - PRIMARY_VOTERVOTEMETHOD_1
  - POLITICAL_PARTY_1
  - POLITICAL_ORGANIZATION_2
  - PRIMARY_ELECTION_DATE_2
  - PRIMARY_VOTERVOTEMETHOD_2
  - POLITICAL_PARTY_2
  - POLITICAL_ORGANIZATION_3
  - PRIMARY_ELECTION_DATE_3
  - PRIMARY_VOTERVOTEMETHOD_3
  - POLITICAL_PARTY_3
  - POLITICAL_ORGANIZATION_4
  - PRIMARY_ELECTION_DATE_4
  - PRIMARY_VOTERVOTEMETHOD_4
  - POLITICAL_PARTY_4
  - POLITICAL_ORGANIZATION_5
  - SCHOOL_ELECTION_DATE
  - SCHOOL_VOTERVOTEMETHOD
  - SCHOOL_ELECTION_DATE_1
  - SCHOOL_VOTERVOTEMETHOD_1
  - SCHOOL_ELECTION_DATE_2
  - SCHOOL_VOTERVOTEMETHOD_2
  - SCHOOL_ELECTION_DATE_3
  - SCHOOL_VOTERVOTEMETHOD_3
  - SCHOOL_ELECTION_DATE_4
  - SCHOOL_VOTERVOTEMETHOD_4
  - CITY_ELECTION_DATE
  - CITY_VOTERVOTEMETHOD
  - CITY_ELECTION_DATE_1
  - CITY_VOTERVOTEMETHOD_1
  - CITY_ELECTION_DATE_2
  - CITY_VOTERVOTEMETHOD_2
  - CITY_ELECTION_DATE_3
  - CITY_VOTERVOTEMETHOD_3
  - CITY_ELECTION_DATE_4
  - CITY_VOTERVOTEMETHOD_4
  - SPECIAL_ELECTION_DATE
  - SPECIAL_VOTERVOTEMETHOD
  - SPECIAL_ELECTION_DATE_1
  - SPECIAL_VOTERVOTEMETHOD_1
  - SPECIAL_ELECTION_DATE_2
  - SPECIAL_VOTERVOTEMETHOD_2
  - SPECIAL_ELECTION_DATE_3
  - SPECIAL_VOTERVOTEMETHOD_3
  - SPECIAL_ELECTION_DATE_4
  - SPECIAL_VOTERVOTEMETHOD_4

election_dates:
  - GENERAL_ELECTION_DATE
  - GENERAL_ELECTION_DATE_1
  - GENERAL_ELECTION_DATE_2
  - GENERAL_ELECTION_DATE_3
  - GENERAL_ELECTION_DATE_4
  - PRIMARY_ELECTION_DATE
  - PRIMARY_ELECTION_DATE_1
  - PRIMARY_ELECTION_DATE_2
  - PRIMARY_ELECTION_DATE_3
  - PRIMARY_ELECTION_DATE_4
  - SCHOOL_ELECTION_DATE
  - SCHOOL_ELECTION_DATE_1
  - SCHOOL_ELECTION_DATE_2
  - SCHOOL_ELECTION_DATE_3
  - SCHOOL_ELECTION_DATE_4
  - CITY_ELECTION_DATE
  - CITY_ELECTION_DATE_1
  - CITY_ELECTION_DATE_2
  - CITY_ELECTION_DATE_3
  - CITY_ELECTION_DATE_4
  - SPECIAL_ELECTION_DATE
  - SPECIAL_ELECTION_DATE_1
  - SPECIAL_ELECTION_DATE_2
  - SPECIAL_ELECTION_DATE_3
  - SPECIAL_ELECTION_DATE_4

general_elections:
  - GENERAL_ELECTION_DATE
  - GENERAL_ELECTION_DATE_1
  - GENERAL_ELECTION_DATE_2
  - GENERAL_ELECTION_DATE_3
  - GENERAL_ELECTION_DATE_4
primary_elections:
  - PRIMARY_ELECTION_DATE
  - PRIMARY_ELECTION_DATE_1
  - PRIMARY_ELECTION_DATE_2
  - PRIMARY_ELECTION_DATE_3
  - PRIMARY_ELECTION_DATE_4
school_elections:
  - SCHOOL_ELECTION_DATE
  - SCHOOL_ELECTION_DATE_1
  - SCHOOL_ELECTION_DATE_2
  - SCHOOL_ELECTION_DATE_3
  - SCHOOL_ELECTION_DATE_4
city_elections:
  - CITY_ELECTION_DATE
  - CITY_ELECTION_DATE_1
  - CITY_ELECTION_DATE_2
  - CITY_ELECTION_DATE_3
  - CITY_ELECTION_DATE_4
special_elections:
  - SPECIAL_ELECTION_DATE
  - SPECIAL_ELECTION_DATE_1
  - SPECIAL_ELECTION_DATE_2
  - SPECIAL_ELECTION_DATE_3
  - SPECIAL_ELECTION_DATE_4

ordered_columns:
  - REGN_NUM
  - FIRST_NAME
  - MIDDLE_NAME
  - LAST_NAME
  - NAME_SUFFIX
  - EFF_REGN_DATE
  - LAST_UPDATED_DATE
  - OLD_ID
  - PHONENO
  - HOUSE_NUM
  - HOUSE_SUFFIX
  - PRE_DIR
  - STREET_NAME
  - STREET_TYPE
  - POST_DIR
  - UNIT_TYPE
  - UNIT_NUM
  - ADDRESS_NON_STD
  - CITY_1
  - STATE_1
  - ZIP_CODE_1
  - ZIP_PLUS_1
  - MAILING_ADDRESS
  - CITY_2
  - STATE_2
  - ZIP_CODE_2
  - ZIP_PLUS_2
  - VOTERSTATUS
  - PARTY
  - POLITICAL_ORGANIZATION
  - GENDER
  - BIRTHDATE
  - COUNTY
  - FEDERAL
  - CONGRESSIONAL
  - STATEWIDE
  - STATE_SENATE
  - STATE_HOUSE
  - JUDICIAL
  - PRECINCT
  - COUNTY_SUPERVISOR
  - COUNTYWIDE
  - TOWNSHIP
  - CITY_COUNCIL_WARD
  - CITY_3
  - COMMUNITY_COLLEGE_DIRECTOR
  - COMMUNITY_COLLEGE
  - SCHOOL_DIRECTOR
  - SCHOOL
  - SANITARY
  - AGRICULTURAL_EXTENSION
  - SOIL_AND_WATER
  - WATER
  - FIRE
  - LAND
  - LAKE
  - LOSST_CONTIGUOUS_CITIES
  - RECREATIONAL
  - RURAL_IMPROVEMENT_ZONE
  - SEWER
  - LIGHT
  - MISCELLANEOUS
  - GENERAL_ELECTION_DATE
  - GENERAL_VOTERVOTEMETHOD
  - GENERAL_ELECTION_DATE_1
  - GENERAL_VOTERVOTEMETHOD_1
  - GENERAL_ELECTION_DATE_2
  - GENERAL_VOTERVOTEMETHOD_2
  - GENERAL_ELECTION_DATE_3
  - GENERAL_VOTERVOTEMETHOD_3
  - GENERAL_ELECTION_DATE_4
  - GENERAL_VOTERVOTEMETHOD_4
  - PRIMARY_ELECTION_DATE
  - PRIMARY_VOTERVOTEMETHOD
  - POLITICAL_PARTY
  - POLITICAL_ORGANIZATION_1
  - PRIMARY_ELECTION_DATE_1
  - PRIMARY_VOTERVOTEMETHOD_1
  - POLITICAL_PARTY_1
  - POLITICAL_ORGANIZATION_2
  - PRIMARY_ELECTION_DATE_2
  - PRIMARY_VOTERVOTEMETHOD_2
  - POLITICAL_PARTY_2
  - POLITICAL_ORGANIZATION_3
  - PRIMARY_ELECTION_DATE_3
  - PRIMARY_VOTERVOTEMETHOD_3
  - POLITICAL_PARTY_3
  - POLITICAL_ORGANIZATION_4
  - PRIMARY_ELECTION_DATE_4
  - PRIMARY_VOTERVOTEMETHOD_4
  - POLITICAL_PARTY_4
  - POLITICAL_ORGANIZATION_5
  - SCHOOL_ELECTION_DATE
  - SCHOOL_VOTERVOTEMETHOD
  - SCHOOL_ELECTION_DATE_1
  - SCHOOL_VOTERVOTEMETHOD_1
  - SCHOOL_ELECTION_DATE_2
  - SCHOOL_VOTERVOTEMETHOD_2
  - SCHOOL_ELECTION_DATE_3
  - SCHOOL_VOTERVOTEMETHOD_3
  - SCHOOL_ELECTION_DATE_4
  - SCHOOL_VOTERVOTEMETHOD_4
  - CITY_ELECTION_DATE
  - CITY_VOTERVOTEMETHOD
  - CITY_ELECTION_DATE_1
  - CITY_VOTERVOTEMETHOD_1
  - CITY_ELECTION_DATE_2
  - CITY_VOTERVOTEMETHOD_2
  - CITY_ELECTION_DATE_3
  - CITY_VOTERVOTEMETHOD_3
  - CITY_ELECTION_DATE_4
  - CITY_VOTERVOTEMETHOD_4
  - SPECIAL_ELECTION_DATE
  - SPECIAL_VOTERVOTEMETHOD
  - SPECIAL_ELECTION_DATE_1
  - SPECIAL_VOTERVOTEMETHOD_1
  - SPECIAL_ELECTION_DATE_2
  - SPECIAL_VOTERVOTEMETHOD_2
  - SPECIAL_ELECTION_DATE_3
  - SPECIAL_VOTERVOTEMETHOD_3
  - SPECIAL_ELECTION_DATE_4
  - SPECIAL_VOTERVOTEMETHOD_4