file_type: csv
state: new_jersey
source: boe
file_class: voter_file
has_headers: False
voter_id: voter_id
county_identifier: county
birthday_identifier: dob
voter_status: status
voter_status_active: Active
voter_status_inactive: Inactive #ID combined with IF
voter_status_active_need_id: Active Need ID #voters need to provide ID or SS after registering
voter_status_active_federal_only: Active-Federal Election Only #very few, to avoid violating NVRA
voter_status_pending: Pending #minors
voter_status_inactive_need_id: Inactive Confirmation-Need ID #funneling this and IF into I
voter_status_inactive_confirmation: Inactive Confirmation #havent voted in several elections
date_format: "%m/%d/%Y"
numeric_county: False
party_identifier: party_code
democratic_party: DEM
republican_party: REP
no_party_affiliation: UNA
green_party: GRE
libertarian_party: LIB
reform_party: REF
us_constitution_party: USC
natural_law_party: NAT
conservative_party: CON
socialist_party: SOC
name_fields:
  - first_name
  - middle_name
  - last_name
  - suffix
address_fields:
  - street_number
  - suff_a
  - suff_b
  - street_name
  - apt_no
  - city
  - municipality
  - zip
format:
  separate_hist: True
  segmented_files: false
primary_key:
  - pre_date
  - post_date
  - voter_id
  - change_type
base_columns:
  pre_date: timestamp
  post_date: timestamp
  voter_id: bigint
  change_type: text
  pre_value: text
  post_value: text
  state: varchar
generated_columns:
  all_history: varchar[]
  party_history: varchar[]
  unabridged_status: varchar
ordered_generated_columns:
  - all_history
  - party_history
  - unabridged_status
summary_columns:
  - totals
  - date
  - state
  - ages_18_34
  - ages_35_49
  - ages_50_64
  - ages_65_130
  - Republican
  - Democratic
  - Other
  - county
summary_types:
  - int
  - timestamp
  - text
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - text
columns:
  county: varchar
  voter_id: bigint
  legacy_id: int
  last_name: varchar
  first_name: varchar
  middle_name: varchar
  suffix: varchar
  street_number: int
  suff_a: varchar
  suff_b: varchar
  street_name: varchar
  apt_no: varchar
  city: varchar
  municipality: varchar
  zip: int
  dob: date
  party_code: varchar
  ward: varchar
  district: varchar
  status: varchar
  congressional: varchar
  legislative: varchar
  freeholder: varchar
  school: varchar
  regional_school: varchar
  fire: varchar
ordered_columns:
  - county
  - voter_id
  - legacy_id
  - last_name
  - first_name
  - middle_name
  - suffix
  - street_number
  - suff_a
  - suff_b
  - street_name
  - apt_no
  - city
  - municipality
  - zip
  - dob
  - party_code
  - ward
  - district
  - status
  - congressional
  - legislative
  - freeholder
  - school
  - regional_school
  - fire
hist_columns:
  - voter_id
  - status_code
  - party_code
  - last_name
  - first_name
  - middle_name
  - prefix
  - suffix
  - sex
  - street_number
  - suffix_a
  - suffix_b
  - street_name
  - apt_no
  - address_line_1
  - address_line_2
  - city
  - state
  - zip5
  - zip4
  - mailing_street_number
  - mailing_suffix_a
  - mailing_suffix_b
  - mailing_street_name
  - mailing_apt_no
  - mailing_address_line_1
  - mailing_address_line_2
  - mailing-city
  - mailing_state
  - mailing_country
  - mailing_zip_code
  - birth_date
  - date_registered
  - county_precinct
  - municipality
  - ward
  - district
  - phone_number
  - election_date
  - election_name
  - election_type
  - election_category
  - ballot_type
hist_columns_type:
  voter_id: bigint
  status_code: char
  party_code: varchar
  last_name: varchar
  first_name: varchar
  middle_name: varchar
  prefix: varchar
  suffix: varchar
  sex: varchar
  street_number: int
  suffix_a: varchar
  suffix_b: varchar
  street_name: varchar
  apt_no: varchar
  address_line_1: varchar
  address_line_2: varchar
  city: varchar
  state: varchar
  zip5: int
  zip4: int
  mailing_street_number: int
  mailing_suffix_a: varchar
  mailing_suffix_b: varchar
  mailing_street_name: varchar
  mailing_apt_no: varchar
  mailing_address_line_1: varchar
  mailing_address_line_2: varchar
  mailing_city: varchar
  mailing_state: varchar
  mailing_country: varchar
  mailing_zip_code: int
  birth_date: date
  date_registered: date
  county_precinct: varchar
  municipality: varchar
  ward: varchar
  district: varchar
  phone_number: int
  election_date: date
  election_name: varchar
  election_type: varchar
  election_category: varchar
  ballot_type: char
county_names:
